#!/bin/sh

#
# Copyright 2017 Maxim Golov <maxim.golov@gmail.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

if [ -z "$1" ] || [ -z "$2" ] ; then
    echo "usage: $0 <input file> <output file>" 1>&2
    exit 1
fi

zcat $1 | awk '
    BEGIN { idx = 1 }
    {
        if (($1 ~ /s/) || ($1 ~ /X/))
            printf("%s string%d\n", $1, idx++);
        else
            print
    }
' | gzip >$2
